name: gmso-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - sympy
  - unyt<=2.9.2
  - boltons
  - lxml
  - pydantic>1.8
  - networkx
  - pytest
  - mbuild>=0.11.0
  - openbabel>=3.0.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.2.1
  - gsd>=2.0
  - parmed>=3.4.3
  - pytest-cov
  - codecov
  - bump2version
  - matplotlib
  - ipywidgets
  - ele>=0.2.0
  - pre-commit
  - pandas
